//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManagementSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Category { get; set; }
        public string Person { get; set; }
        public string ExpenseType { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Payments { get; set; }
        public string IsLuxury { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Regular { get; set; }
        public string Currency { get; set; }
    }
}
