//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManagementSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyIncome
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string IncomeSrc { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Comments { get; set; }
        public string Currency { get; set; }
    }
}
