//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManagementSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public int id { get; set; }
        public string ServiceLocation { get; set; }
        public string ServiceType { get; set; }
        public string SupplierName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<short> MonthlyPrice { get; set; }
        public string SupplierContactDetails { get; set; }
        public string Comments { get; set; }
    }
}
