//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManagementSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialEvent
    {
        public int Id { get; set; }
        public short Month { get; set; }
        public short Year { get; set; }
        public string EventDescription { get; set; }
        public short EventPrice { get; set; }
    }
}
